server:
  port: 9081

dubbo:
  cloud:
    subscribed-services: user-service
  protocols:
    dubbo:
      port: -1

spring:
  #dubbo配置
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848